--- 
abstract: Does your process have access to the web
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: LWP-Online
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  LWP::Simple: 0
  perl: 5.005
version: 0.03
