---
abstract: 'Does your process have access to the web'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: LWP::Online
name: LWP-Online
no_index:
  directory:
    - inc
    - t
requires:
  LWP::Simple: 0
  URI: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.06
